import { ROLES } from './constants'

export const PERMISSIONS = {
  // Users
  CREATE_USER: [ROLES.ADMIN],
  EDIT_USER: [ROLES.ADMIN],
  DELETE_USER: [ROLES.ADMIN],
  VIEW_ALL_USERS: [ROLES.ADMIN],

  // Groups
  CREATE_GROUP: [ROLES.ADMIN],
  EDIT_GROUP: [ROLES.ADMIN],
  DELETE_GROUP: [ROLES.ADMIN],

  // Subjects
  CREATE_SUBJECT: [ROLES.ADMIN],
  EDIT_SUBJECT: [ROLES.ADMIN],

  // Assignments
  CREATE_ASSIGNMENT: [ROLES.TEACHER],
  TOGGLE_UPLOAD: [ROLES.TEACHER],
  GRADE_SUBMISSION: [ROLES.TEACHER],
  SUBMIT_ASSIGNMENT: [ROLES.STUDENT],

  // Attendance
  MARK_ATTENDANCE: [ROLES.TEACHER],
  VIEW_OWN_ATTENDANCE: [ROLES.STUDENT],

  // Grades
  ENTER_GRADES: [ROLES.TEACHER],
  VIEW_OWN_GRADES: [ROLES.STUDENT],

  // Resources
  CREATE_RESOURCE: [ROLES.TEACHER, ROLES.ADMIN],
  DELETE_RESOURCE: [ROLES.TEACHER, ROLES.ADMIN],
}

export const can = (userRole, permission) => PERMISSIONS[permission]?.includes(userRole) ?? false
